Fixed inconsistent documentation for nbunch parameter in DiGraph.edges()
networkx/networkx pull request #5037
Opened 2021-08-27 12:11 UTC by anutosh491

Closes #4985 
On going through the code ,I found that the "nbunch" parameter has been used more than a couple of times and the description for all of those was misleading . Hence I have fixed the description of each of those as required.

2021-08-27 23:12 UTC, rossbar requested changes

2021-08-27 23:12 UTC, rossbar commented on networkx/classes/digraph.py
> +            The view will only report edges from these nodes (outgoing if directed).
The "(outgoing if directed)" seems unnecessary here, since this is in the docstring for the DiGraph class (so "if directed" will always be true).

2021-08-28 09:53 UTC, anutosh491 commented
Sure , will update the docstring changes as requested !

2021-10-15 18:55 UTC, rossbar reviewed
I think the easiest way to move this forward is to restrict the changes to the `edges` property for now. I think the changes to `degree`, `in_degree`, and `out_degree` are actually incorrect.

The wording for the docstrings of those properties could definitely also be improved, but in the interest of getting this unstuck I'd be in favor of rolling back those changes and addressing them in a followup PR/issue.

2021-12-11 22:06 UTC, rossbar approved these changes
In the interest of getting this one unstuck, I went ahead and reverted the changes to the `degree`, `in_degree`, and `out_degree` docstrings as I had mentioned. I agree that the wording there may also need some updating, but I'd vote for handling that in a separate PR - no sense in blocking this correction. I also went ahead and updated the comments in the `Examples` section to maintain consistency with the new wording.

2021-12-12 02:51 UTC, dschult commented
Should these same changes (docs for edges method) also be bumped to the undirected graph class?  How about to the multigraph classes?   It is accurate for all of them and should probably be improved in the same way.

2021-12-12 04:51 UTC, rossbar commented
> Should these same changes (docs for edges method) also be bumped to the undirected graph class?

Good question - I think this specific wording makes sense for the directed graphs because in that case it does explicitly limit to out-edges that originate from the node(s) in nbunch. In the undirected case, there is no longer a distinction between an incoming or outgoing edge, so the "incident to" isn't as much of an issue, though maybe there's a better way to say it. Maybe "edges that include these nodes" or "edges that contain these nodes"? I don't think either of those is a clear improvement over "edges incident to these nodes". Any other suggestions?

2021-12-13 01:07 UTC, dschult commented
I would recommend using the exact same wording as for the directed case in the undirected case. Then the docs are the same for both classes and still accurate in both classes. Briefly looking at the two multigraph classes, I think the same wording can be used there too. I guess I am just saying it is just universally better wording. :}

2021-12-13 04:18 UTC, dschult approved these changes
LGTM   Thanks!!

2021-12-13 04:18 UTC, merged

2021-12-13 06:55 UTC, anutosh491 commented
Thanks @dschult