Update `draw_<layout>` docstrings with usage examples
networkx/networkx pull request #5264
Opened 2022-01-15 21:47 UTC by rossbar

This PR adds to the existing `draw_<layout>` convenience functions to emphasize their intended use-case and highlight using the layout functions explicitly for more involved usages. I've done this primarily by adding a short line to the extended summary explaining what the convenience function wraps, as well as a `Notes` and `See Also` section that highlight other use-cases.

This also closes #5215 by updating the parameters and simplifying the argument parsing. Technically this is a change to the signature, but I don't think it needs any sort of warning as the behavior is equivalent.

This addresses most of https://github.com/networkx/networkx/discussions/5220#discussioncomment-1961800, though there is still the matter of adding convenience functions for the missing layouts, which I propose to do in a separate PR.

2022-01-24 15:22 UTC, MridulS requested changes
LGTM, Thanks! Just a typo here :)

2022-01-24 15:22 UTC, MridulS commented on networkx/drawing/nx_pylab.py
> +        >>> pos = nx.spring_layout(G)
```suggestion
        >>> pos = nx.shell_layout(G)
```

2022-01-24 19:31 UTC, MridulS approved these changes

2022-02-12 17:17 UTC, jarrodmillman approved these changes

2022-02-12 17:17 UTC, merged