PR to find a proportional cake allocation
networkx/networkx pull request #6367
Opened 2023-01-15 12:03 UTC by EranK123

Hello, I am a student at Ariel University under Dr Erel Segal.(https://github.com/erelsgl)
As a part of Research Algorithms course I have implemented an algorithm for finding a proportional cake allocation in a almost bridgeless graph. The Implementation is based on the article: (https://arxiv.org/abs/1910.14129).

2023-01-16 10:19 UTC, EranK123 commented
Done

2023-01-16 14:47 UTC, erelsgl requested changes

2023-01-16 14:47 UTC, erelsgl commented on networkx/algorithms/approximation/contiguous_oriented_labeling.py
> +This file admits a contiguous oriented labeling in an almost bridgeless graph.
The title should be much more detailed. It should contain a description of what is contiguous oriented labeling, what is almost bridgeless, what paper the algorithm comes from (including title, authors and link), and who the programmer is.

2023-01-16 14:47 UTC, erelsgl commented on networkx/algorithms/approximation/contiguous_oriented_labeling.py
> +def graph_example1():
All examples used in the doctest should be inside the doctest.

2023-01-16 14:47 UTC, erelsgl commented on networkx/algorithms/approximation/contiguous_oriented_labeling.py
> +    >>> get_contiguous_oriented_labeling(graph_example1())
Also, it is not clear why the "InEdgeView" is in the expected output. The expected output should contain only what is needed to verify the algorithm.

2023-01-16 14:47 UTC, erelsgl commented on networkx/algorithms/approximation/contiguous_oriented_labeling.py
> +    This function takes an almost bridgeless graph and adds an edge so it makes it bridgeless
Add explanations and examples. See here: https://github.com/networkx/networkx/pull/5585/files  how good examples look like.

2023-01-16 14:47 UTC, erelsgl commented on networkx/algorithms/approximation/contiguous_oriented_labeling.py
> +    for (
This should be a single line: 
```
for edge in graph edges:
```

2023-01-16 14:47 UTC, erelsgl commented on examples/algorithms/proportional_cake_allocation.py
> +def graph_example1():
Functions used only in doctests should be defined in the doctest

2023-01-16 14:47 UTC, erelsgl commented on examples/algorithms/proportional_cake_allocation.py
> +    """
doctest is missing

2024-03-08 05:39 UTC, rossbar reviewed
This has been stale for a while so I will go ahead and close it.

2024-03-08 05:39 UTC, closed without merging