added doc examples for distance_measures
networkx/networkx pull request #6577
Opened 2023-03-29 19:48 UTC by Qudirah

fixes for #6575

2023-04-02 19:04 UTC, rossbar requested changes

2023-04-02 19:04 UTC, rossbar commented on networkx/algorithms/approximation/distance_measures.py
> +    >>> from networkx.algorithms.approximation.distance_measures import diameter
We want users to call `nx.diameter`, not import the function from this (very deep) package!

2023-04-15 13:43 UTC, MridulS commented
@Qudirah just wanted to bump this up :)

If you have the time could you please fix up the requested changes in the PR, so I can go through and review them? Thanks for your contributions!!

2023-04-15 13:51 UTC, Qudirah commented
@MridulS i just got caught up with something else. Will attend to everything real soon. Sorry.

2023-04-19 22:18 UTC, dschult commented on networkx/algorithms/approximation/distance_measures.py
> +    >>> G.add_edges_from([(2,3),(3,5),(5,2)]) #directed graph
The cycle_graph function can be used for this case:
```suggestion
    >>> G = nx.cycle_graph([2, 3, 5], create_using=nx.DiGraph)  # directed graph
```

2023-05-16 14:26 UTC, closed without merging