add doc examples to dominating_sets.py
networkx/networkx pull request #6578
Opened 2023-03-29 20:15 UTC by Qudirah

fixes for #6575

2023-04-02 19:09 UTC, rossbar requested changes

2023-04-02 19:09 UTC, rossbar commented on networkx/algorithms/approximation/dominating_set.py
> +    >>> from networkx.algorithms.approximation.dominating_set import min_weighted_dominating_set
Same here: `nx.approximation.min_weighted_dominating_set`

2023-04-02 19:09 UTC, rossbar commented on networkx/algorithms/approximation/dominating_set.py
> +    >>> G.add_edges_from(edges)
This is more concisely written as:

```suggestion
    >>> G = nx.Graph([(0, 1), (0, 3), (1, 2), (1, 3), (1, 4)])
```

Also note the spaces between the tuples - we use `black` formatting for the docstring examples as well. This should be automatically applied when you commit if you have the `pre-commit` hooks installed: take a look at the [contributor guide](https://networkx.org/documentation/latest/developer/contribute.html#development-workflow) for info on how to properly set this up.

2023-04-19 22:20 UTC, dschult commented on networkx/algorithms/approximation/dominating_set.py
> +    >>> G.add_edges_from(edges)
```suggestion
    >>> G = nx.Graph([(1, 0), (1, 2), (1, 3), (1, 4), (0, 3)])
```

2023-05-16 14:26 UTC, closed without merging