Fix typos
networkx/networkx pull request #7012
Opened 2023-10-12 05:33 UTC by kianmeng

Found via `codespell -L
ans,wth,nd,ist,dout,coo,childs,nin,ded,ons,nam,perfor,malins,stoer,mis,abritrary,commun,ser,te,equil,numer,thi,clos,infor,hax,pich,inout,alledges`

2023-10-12 07:03 UTC, jarrodmillman requested changes
Once those two changes are reverted, this should be good to go. Thanks!!

2023-10-12 07:03 UTC, jarrodmillman commented on CODE_OF_CONDUCT.rst
> +a conflict of interest in handling it, then they will recurse themselves from
```suggestion
a conflict of interest in handling it, then they will recuse themselves from
```

This was correct.

2023-10-12 07:03 UTC, jarrodmillman commented on examples/geospatial/schools.shp.xml
> -ADEQ assumes no responsibility for errors arising from misuse of the data or maps derived from the data. ADEQ disclaims any liability for injury, damage or loss that might result from the use of this
I don't not what changed. But this is a dataset, so we should leave it alone.

2023-10-13 14:49 UTC, merged

2023-10-14 09:09 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: