Solved "no plot in networkx/examples/algorithms/plot_iterated_dynamic…
networkx/networkx pull request #7665
Opened 2024-10-10 14:53 UTC by shubhamvk03

2024-10-10 15:51 UTC, jarrodmillman commented on examples/algorithms/plot_iterated_dynamical_systems.py
>  print("Shortest path from 177 to 153 is:")
```suggestion
G = cubing_153_digraph(nmax)
print("Resulting digraph has", len(G), "nodes and", G.size(), " edges")
print("Shortest path from 177 to 153 is:")

# Plotting the resulting digraph
plt.figure(figsize=(12, 12))  # Set up the figure size
pos = nx.spring_layout(G)  # Use a layout for visual spacing
nx.draw(
    G,
    pos,
    with_labels=True,
    node_size=50,
    font_size=8,
    node_color="skyblue",
    edge_color="gray",
)
plt.title("Cubing 153 Digraph for Iterated Dynamical System")
plt.show()  # Display the plot
```

The graph needs to be constructed before you can plot it.

2024-10-10 15:55 UTC, jarrodmillman commented on examples/algorithms/plot_iterated_dynamical_systems.py
>  G = cubing_153_digraph(nmax)
```suggestion
G = cubing_153_digraph(nmax)

# Plotting the resulting digraph
plt.figure(figsize=(12, 12))  # Set up the figure size
pos = nx.spring_layout(G)  # Use a layout for visual spacing
nx.draw(
    G,
    pos,
    with_labels=True,
    node_size=50,
    font_size=8,
    node_color="skyblue",
    edge_color="gray",
)
plt.title("Cubing 153 Digraph for Iterated Dynamical System")
plt.show()  # Display the plot

```

2024-10-10 15:56 UTC, jarrodmillman commented on examples/algorithms/plot_iterated_dynamical_systems.py
>  G = cubing_153_digraph(nmax)
The graph needs to be constructed before you can plot it.

2024-10-18 17:20 UTC, rossbar requested changes
One obvious issue with the changes is that the runtime for the example goes from <1s to >600s which IMO is a major blocker. Given what's changed I suspect the layout as being the culprit. Also, the plot [is not particularly informative nor visually appealing](https://output.circle-artifacts.com/output/job/ad9c75d3-113d-4a8e-ba41-204c384aa062/artifacts/0/doc/build/html/auto_examples/algorithms/plot_iterated_dynamical_systems.html#the-3n-1-problem) as currently configured. I'd personally vote to:
 1. Remove node labels
 2. Use default node and edge colors
 3. Remove self-loop edges from the visualization

Another consideration: the preferred matplotlib pattern is to modify figure and axes instances directly rather than use `plt.` to modify the current instance. For example:

```python
>>> fig, ax = plt.subplots()
>>> nx.draw(G, pos, ax=ax)
>>> ax.set_title("Cubing 153 Digraph for Iterated Dynamical System")
```

etc.

2025-02-06 23:10 UTC, rossbar reviewed
This one has been stale for a while so I will go ahead and close it. If interested in continuing, please feel free to address the previous comments and reopen!

2025-02-06 23:10 UTC, closed without merging